// Generated by BUCKLESCRIPT VERSION 6.0.1, PLEASE EDIT WITH CARE
'use strict';


function describe(description, tests) {
  return /* record */[
          /* description */description,
          /* tests */tests
        ];
}

function it(name, test) {
  return /* record */[
          /* name */name,
          /* f */test
        ];
}

exports.describe = describe;
exports.it = it;
/* No side effect */
