// Generated by BUCKLESCRIPT VERSION 6.0.1, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function print_results(results) {
  return List.iter(Pervasives.print_string, List.map((function (status) {
                    if (status) {
                      return "Failed with \"" + (status[0] + "\"\n");
                    } else {
                      return "OK\n";
                    }
                  }), results));
}

exports.print_results = print_results;
/* No side effect */
