// Generated by BUCKLESCRIPT VERSION 6.0.1, PLEASE EDIT WITH CARE
'use strict';

var Dsl$WebTestProtocol = require("./dsl.bs.js");
var Printer$WebTestProtocol = require("./printer.bs.js");
var Web_test$WebTestProtocol = require("./web_test.bs.js");

Printer$WebTestProtocol.print_results(Web_test$WebTestProtocol.run_suite(Dsl$WebTestProtocol.describe("Some Suite", /* :: */[
              Dsl$WebTestProtocol.it("true is true", (function (param) {
                      var match = true === true;
                      if (match) {
                        return /* Success */0;
                      } else {
                        return /* Failure */["true wasn't true"];
                      }
                    })),
              /* :: */[
                Dsl$WebTestProtocol.it("false is not true", (function (param) {
                        var match = false === false;
                        if (match) {
                          return /* Failure */["Holy moly, we're in trouble!"];
                        } else {
                          return /* Success */0;
                        }
                      })),
                /* [] */0
              ]
            ])));

/*  Not a pure module */
